server:
  port: 8080
### 配置数据库的连接方式
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:\\db\\sqlite\\springboot.db
    username:
    password:
### sqlite需要自己配置连接方式
  jpa:
    database-platform: com.fchen.util.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
 path: /var/logs/
 file: basket.log
 level:
  root: WARN
   org.springframework.security: DEBUG